// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9xFyPIu2-0vhaEq1Qxr58Ho86wfHMRA0',
    appId: '1:150256148315:android:f483a434e881f04995447e',
    messagingSenderId: '150256148315',
    projectId: 'bloomy-app-4845c',
    storageBucket: 'bloomy-app-4845c.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO2Wcc-2_rhnuCs11YcY_yybgf0Exc2AQ',
    appId: '1:150256148315:web:448c6fbfecea8f2395447e',
    messagingSenderId: '150256148315',
    projectId: 'bloomy-app-4845c',
    authDomain: 'bloomy-app-4845c.firebaseapp.com',
    storageBucket: 'bloomy-app-4845c.firebasestorage.app',
    measurementId: 'G-MHCLVS7EER',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb_WL5eqokCinlscq1MKnUQ4Pql8eb39s',
    appId: '1:150256148315:ios:a82c4719f6345dc695447e',
    messagingSenderId: '150256148315',
    projectId: 'bloomy-app-4845c',
    storageBucket: 'bloomy-app-4845c.firebasestorage.app',
    iosBundleId: 'com.example.bloomy',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb_WL5eqokCinlscq1MKnUQ4Pql8eb39s',
    appId: '1:150256148315:ios:a82c4719f6345dc695447e',
    messagingSenderId: '150256148315',
    projectId: 'bloomy-app-4845c',
    storageBucket: 'bloomy-app-4845c.firebasestorage.app',
    iosBundleId: 'com.example.bloomy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO2Wcc-2_rhnuCs11YcY_yybgf0Exc2AQ',
    appId: '1:150256148315:web:c17a580e113a7a4895447e',
    messagingSenderId: '150256148315',
    projectId: 'bloomy-app-4845c',
    authDomain: 'bloomy-app-4845c.firebaseapp.com',
    storageBucket: 'bloomy-app-4845c.firebasestorage.app',
    measurementId: 'G-H1RNTYDMME',
  );
}
